Feature/find puuid
arturrpereira/lol-composition-analyzer pull request #7
Opened 2024-11-20 15:16 UTC by NogueiraMat

Adding the find_puuid service, which will fetch summoner IDs from the 'find_summonerid_queue' and retrieve the puuid data by making a request to the RIOT API. Then, it will send a message to the 'analyzer' (a topic exchange) with the puuid found.

2024-11-20 15:38 UTC, arturrpereira commented
feat(rabbitmq): add rabbitmq connection class -> Não entendi o contexto desse commit. O arquivo já consta na develop, se foi alguma melhoria ou correção de bug recomendo a abertura de uma nova branch e um novo PR para manter o contexto dessa branch(find_puuid) íntegro

2024-12-11 01:13 UTC, arturrpereira requested changes

2024-12-11 01:13 UTC, arturrpereira commented on src/find_puuid_service/main.py
> +conn.exchange_declare(exchange="analyzer", exchange_type="topic")
Trocar para exchange "direct"

2024-12-11 01:13 UTC, arturrpereira commented on src/find_puuid_service/main.py
> +        routing_key = f"puuid.{puuid}"
Apenas utilizar a routing key "puuid"

2024-12-11 11:31 UTC, NogueiraMat commented on src/find_puuid_service/main.py
> +conn.exchange_declare(exchange="analyzer", exchange_type="topic")
Mudança realizada.

2024-12-11 11:32 UTC, NogueiraMat commented on src/find_puuid_service/main.py
> +        routing_key = f"puuid.{puuid}"
Mudança realizada

2024-12-12 01:06 UTC, arturrpereira approved these changes

2024-12-12 01:06 UTC, merged